### ISSUE TITLE
Invalid bash.exe path when running in 32-bit mode

### ISSUE THREAD

**Issue by giovdk21** [giovdk21/wsl-bash-tools#1]
```
> Executing task: C:\dev\utils\wsl-bash-tools\wsl-bash-run.bat uname -a <

& : The term 'C:\Windows\System32\bash.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
```

reported by @octotot

https://github.com/Microsoft/vscode/issues/22663#issuecomment-315205545

**Comment by stankul** [comment]
That was indeed the issue, works now. Thank you!

**Comment by giovdk21** [comment]
Thanks for confirming this @stankul 

Did you find other issues / are you finding it useful?

**Comment by stankul** [comment]
No problem @giovdk21 
Not much use, unfortunately. I was trying to make VS Code work with WSL python and/or git, but gave up.
